aaqilrk/ecommerce-website

- controllers/adminController.js
- models/admin.js
- routes/admin.js
- routes/index.js
* Admin model has been added.
* Controller for admin has been created
* Route for admin has been created
* route/index.js has been updated
> add admin model

- routes/admin.js
* admin model is now being created 
* changed route/admin.js to resolve error 
Closes #8
> resolved admin model error

- controllers/bookController.js
- models/admin.js
- models/book.js
- routes/book.js
- routes/index.js
* add model book in models/
* add book controller in controllers/
* add book route in routes/
* connected book route to routes/index.js
* made relation between book and admin
* closes #1
> Add model book

- controllers/orderController.js
- models/book.js
- models/customer.js
- models/order.js
- routes/index.js
- routes/order.js
*  add model order in models/
* add order controller in controllers/
* add order route in routes/
* connected  order route to routes/index.js
* made relation between order and  customer
* made relation between order and  book
* closes create order model #2
> Create model order

- models/order.js
* corrected order attributes spelling 
* closes #19
> correct order attributes spelling

- controllers/bookController.js
- models/book.js
- models/category.js
* add model category in models/
* made relation between category and book
* closes #3
> create model category, create relation category and book

- controllers/bookController.js
- models/author.js
- models/book.js
* add model author in models/
* made relation between author and book
* closes #4
> create model author, create relation author and book

- assets/css/register.css
- views/home.ejs
- views/layout.ejs
- views/register.ejs
* add front end to register page
*  closes #14
> add front end to register page

- assets/css/login.css
- views/login.ejs
* added front end to login page
*  closes  #13
> add front end login page

- assets/css/layout.css
- assets/css/login.css
- assets/css/register.css
> updated CSS

- controllers/cartController.js
- models/cart.js
- routes/cart.js
- routes/index.js
* add model cart in models/
* add cart controller in controllers/
* add cart route in routes/
* connected cart route to routes/index.js
* made relation between book and customer
* closes #5
> Add model cart

- config/sequelize.js
- models/author.js
- models/book.js
- models/cart.js
- models/category.js
- models/customer.js
- models/order.js
> Update model order

- controllers/homeController.js
- views/home.ejs
> render all books in homepage

- app.js
- controllers/userController.js
- middleware/flash.js
- middleware/passportLocalStrategy.js
- package-lock.json
- package.json
- views/layout.ejs
> add flash messages

- .gitignore
- controllers/homeController.js
- models/book.js
- views/home.ejs
> add feature to store and display book image

- assets/css/register.css
- views/register.ejs
> fix register page

- assets/css/header.css
- views/_header.ejs
> add header

- assets/css/footer.css
- views/_footer.ejs
> add footer

- app.js
- assets/css/footer.css
- assets/css/home.css
- assets/css/layout.css
- views/home.ejs
- views/layout.ejs
> Frontend product page

- assets/css/cart.css
- assets/css/home.css
- assets/css/layout.css
- controllers/cartController.js
- controllers/homeController.js
- controllers/userController.js
- middleware/passportLocalStrategy.js
- models/cart.js
- routes/cart.js
- routes/index.js
- views/_header.ejs
- views/cart.ejs
- views/home.ejs
> Add cart functionality

- controllers/homeController.js
> fix homepage bug

- controllers/cartController.js
> add cart flash messages

- controllers/cartController.js
- middleware/flash.js
- views/layout.ejs
> update cart flash messages

- assets/css/register.css
- views/register.ejs
> update register page

- assets/css/header.css
- views/_header.ejs
> add sign out option in header
